name: 'global_container_trade'
version: '1.0.0'
profile: 'global_container_trade'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  global_container_trade:
    staging:
      +schema: INTERMEDIATE_RAW
    intermediate:
      +schema: INTERMEDIATE_INTERMEDIATE
    marts:
      +schema: INTERMEDIATE_MART
    analytics:
      +schema: INTERMEDIATE_ANALYTICS

seeds:
  global_container_trade:
    +schema: INTERMEDIATE_RAW
    +quote_columns: false
