version: 2

sources:
  - name: raw
    schema: RAW
    tables:
      - name: container_events

models:
  - name: stg_container_events
    columns:
      - name: container_id
        tests:
          - not_null
      - name: event_time
        tests:
          - not_null
      - name: event_type
        tests:
          - not_null
