version: 2

sources:
  - name: intermediate_raw
    schema: INTERMEDIATE_RAW
    tables:
      - name: container_events
      - name: container_moves
      - name: container_types
      - name: ports
