version: 2

models:
  - name: dim_event_types
    description: "Reference table of normalized event types."
    columns:
      - name: event_type
        tests:
          - not_null
          - unique

  - name: dim_ports
    description: "Standardized global port reference."
    columns:
      - name: port_code
        tests:
          - not_null
          - unique

  - name: dim_container_status
    description: "Reference for latest container status."
    columns:
      - name: current_status
        tests:
          - not_null

  - name: fct_container_journey
    description: "Analytics fact table describing full container journey."
    columns:
      - name: container_id
        description: "Unique identifier per journey."
        tests:
          - unique
          - not_null

      - name: total_events
        description: "Number of lifecycle events for the container."
      - name: total_transit_days
        description: "Transport duration based on first and last events."
