version: 2

models:
  - name: fct_container_journey
    description: "Fact table containing summarized journey metrics for each container."
    columns:
      - name: container_id
        tests:
          - not_null
          - unique

      - name: total_events
        tests:
          - not_null

      - name: total_transit_days
        tests:
          - not_null

# -----------------------------
# DIMENSIONAL MODELS
# -----------------------------

  - name: dim_ports
    description: "Port dimension table containing port codes, country codes, and (future) port metadata."
    columns:
      - name: port_code
        description: "Unique code for identifying the port."
        tests:
          - not_null
          - unique

  - name: dim_event_types
    description: "Standardized list of container movement event types."
    columns:
      - name: event_type
        description: "Raw event type extracted from container movement logs."
        tests:
          - not_null
          - unique
      - name: event_category
        description: "High-level event grouping (Loading, Discharge, Transshipment, etc.)."

  - name: dim_container_status
    description: "Container end-state dimension table based on journey summary."
    columns:
      - name: current_status
        description: "Latest/Final status of the container."
        tests:
          - not_null
          - unique
      - name: status_group
        description: "Grouped status (Completed, In Transit, On Hold, etc.)."
