version: 2

models:
  - name: int_container_flow
    description: "Cleaned, ordered, and enriched container event stream."
    columns:
      - name: container_id
        tests:
          - not_null

      - name: event_sequence
        tests:
          - not_null

      - name: event_time
        tests:
          - not_null
